# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2a343606f60c31c775ca14cbc861711b6c7211d5ade3e7c7c15ffeef95ceb69fee2cf88d926e5b907e27168172c268489209260290d9e273ceef02223cc56ab

test:
  secret_key_base: 952ef99753afaa286bcf2583928dcd9ec96660acdbc345de76bc410379525126353eef076b2e2fe99b937e16f2e7467922eb3865ff3decb1e14138e3ed2153b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
